CREATE TABLE IF NOT EXISTS PasswordResetToken (
    TokenID INTEGER PRIMARY KEY AUTOINCREMENT,
    UserID INTEGER NOT NULL,
    Token TEXT NOT NULL,
    ExpiresAt TEXT NOT NULL,
    IsUsed INTEGER NOT NULL DEFAULT 0,
    CreatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
